## Hyperparameter Tuning

In [12]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score,GridSearchCV,RandomizedSearchCV 

In [7]:
iris = load_iris()

 #### Manually try different parameters using _cross_val_score_

In [8]:
from sklearn.svm import SVC

In [9]:
cross_val_score(SVC(kernel='linear', C=10, gamma='auto'), iris.data, iris.target, cv=5)

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [10]:
cross_val_score(SVC(kernel='rbf', C=10, gamma='auto'), iris.data, iris.target, cv=5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [11]:
cross_val_score(SVC(kernel='rbf', C=20, gamma='auto'), iris.data, iris.target, cv=5)

array([0.96666667, 1.        , 0.9       , 0.96666667, 1.        ])

_Instead of above approach , we can use a for loop to change parameters_

In [13]:
kernels = ['rbf', 'linear']
C = [1,10,20]
avg_scores = {}

for k in kernels:
    for c in C:
        cv_scores = cross_val_score( SVC(kernel=k, C=c, gamma='auto') ,iris.data, iris.target, cv = 5)
        avg_scores[k + '_' + str(c)] = np.average(cv_scores)
        
avg_scores

{'rbf_1': 0.9800000000000001,
 'rbf_10': 0.9800000000000001,
 'rbf_20': 0.9666666666666668,
 'linear_1': 0.9800000000000001,
 'linear_10': 0.9733333333333334,
 'linear_20': 0.9666666666666666}

from above results, rbf with C=1, C=10 and linear with C=1 gives best performance